import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar';
export type Direction = 'ltr' | 'rtl';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.testimonials': 'Testimonials',
    'nav.getStarted': 'Get Started',
    
    // Hero Section
    'hero.title': 'Your AI-Powered',
    'hero.titleHighlight': 'Business Growth Partner',
    'hero.description': 'Get strategic business insights, market research, sales optimization, and trend analysis - all from one intelligent AI consultant.',
    'hero.cta': 'Start Consulting with AYN',
    'hero.joinBusiness': 'Join 10,000+ growing businesses',
    'hero.readyToAnalyze': 'Ready to analyze your business',
    'hero.aiConsultantQuote': 'I can help you with market research, competitive analysis, sales optimization, and strategic planning. What would you like to explore first?',
    
    // Features Section
    'features.title': 'Comprehensive Business Intelligence',
    'features.subtitle': 'One AI agent with multiple specialized capabilities to accelerate your business growth',
    'features.marketResearch.title': 'Market Research',
    'features.marketResearch.description': 'Get strategic business insights with comprehensive market analysis and competitive intelligence.',
    'features.salesOptimization.title': 'Sales Optimization',
    'features.salesOptimization.description': 'Optimize your sales funnel and conversion rates with data-driven recommendations.',
    'features.trendAnalysis.title': 'Trend Analysis',
    'features.trendAnalysis.description': 'Analyze market trends and identify emerging opportunities before your competitors.',
    'features.strategicPlanning.title': 'Strategic Planning',
    'features.strategicPlanning.description': 'Comprehensive business consulting and strategic planning powered by advanced AI.',
    
    // Testimonials Section
    'testimonials.title': 'Trusted by Industry Leaders',
    'testimonials.subtitle': 'See how AYN is transforming businesses worldwide',
    'testimonials.sarah.quote': 'AYN transformed our business strategy. The insights were game-changing.',
    'testimonials.marcus.quote': 'The market analysis capabilities are incredibly detailed and actionable.',
    'testimonials.emma.quote': 'AYN\'s trend predictions helped us pivot our strategy at the perfect time.',
    
    // Footer
    'footer.copyright': '© 2024 AYN AI Business Consulting. All rights reserved.',
    
    // Mode names
    'modes.general': 'General',
    'modes.nenMode': 'Nen Mode',
    'modes.researchPro': 'Research Pro',
    'modes.pdfAnalyst': 'PDF Analyst',
    'modes.visionLab': 'Vision Lab',
    'modes.civilEngineering': 'Civil Engineering',
    
    // Header elements
    'header.aynBusinessConsole': 'AYN Business Console',
    'header.chat': 'Chat',
    'header.admin': 'Admin',
    
    // Dashboard
    'dashboard.loading': 'Loading AYN...',
    'dashboard.chatLoaded': 'Chat Loaded',
    'dashboard.loadedConversation': 'Loaded conversation',
    'dashboard.newChatDesc': 'You can now start a fresh conversation with AYN.',
    'dashboard.chatsDeleted': 'Chats Deleted',
    'dashboard.successfullyDeleted': 'Successfully deleted',
    'dashboard.conversations': 'conversation(s)',
    'dashboard.templates.marketAnalysis': 'Market Analysis',
    'dashboard.templates.marketAnalysisPrompt': 'Analyze the current market trends and opportunities in my industry',
    'dashboard.templates.salesFunnel': 'Sales Funnel Audit',
    'dashboard.templates.salesFunnelPrompt': 'Review my sales process and identify conversion bottlenecks',
    'dashboard.templates.competitorResearch': 'Competitor Research',
    'dashboard.templates.competitorResearchPrompt': 'Research my main competitors and their strategies',
    'dashboard.templates.growthStrategy': 'Growth Strategy',
    'dashboard.templates.growthStrategyPrompt': 'Develop a comprehensive growth strategy for scaling my business',
    
    // Mode-specific placeholders (stored as JSON strings)
    'placeholders.General': '["Ask about your business strategy...", "How can I help optimize your operations?", "What business challenge are you facing?"]',
    'placeholders.Nen Mode ⚡': '["Get expert strategic insights...", "Request comprehensive analysis...", "Need specialized consultation?"]',
    'placeholders.Research Pro': '["What market trends should I research?", "Find the latest industry data...", "Which competitor should I analyze?"]',
    'placeholders.PDF Analyst': '["Upload your business document...", "Let me review your files...", "Upload PDF for analysis..."]',
    'placeholders.Vision Lab': '["Upload image for analysis...", "Analyze charts and visuals...", "Share visual content..."]',
    
    // Legacy placeholders (keeping for backward compatibility)
    'dashboard.placeholders.askAyn': 'Ask AYN anything about your business...',
    'dashboard.placeholders.increaseRevenue': 'How can I increase my revenue?',
    'dashboard.placeholders.marketTrends': 'What are the latest market trends?',
    'dashboard.placeholders.competitionStrategy': 'Analyze my competition strategy...',
    'dashboard.placeholders.optimizeSales': 'How do I optimize my sales funnel?',
    'dashboard.placeholders.growthOpportunities': 'What growth opportunities exist?',
    'dashboard.placeholders.pricingStrategy': 'Help me with pricing strategy...',
    'dashboard.placeholders.targetMarket': 'Research my target market...',
    
    // Auth & Access
    'auth.termsRequired': 'Terms Required',
    'auth.termsRequiredDesc': 'Please accept the terms and conditions before using AYN AI.',
    'auth.accessRequired': 'Access Required',
    'auth.accessRequiredDesc': 'You need active access to use AYN. Please contact our team.',
    'auth.welcomeTitle': 'Welcome to AYN!',
    'auth.welcomeDesc': 'You can now start using AYN AI Business Consulting services.',
    
    // Errors & Messages
    'error.usageLimit': 'Usage Limit Reached',
    'error.usageLimitDesc': 'You\'ve reached your monthly message limit. Please contact support or wait for next month\'s reset.',
    'error.systemError': 'System Error',
    'error.systemErrorDesc': 'Unable to process your request. Please try again.',
    
    // Common
    'common.signOut': 'Sign Out',
    'common.settings': 'Settings',
    'common.admin': 'Admin',
    'common.chat': 'Chat',
    'common.language': 'Language',
    'common.noConversations': 'No conversations yet. Start chatting with AYN!',
    'common.newChat': 'New Chat',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.thinking': 'Thinking...',
    'common.user': 'User',
    'common.quickStart': 'Quick Start',
    'common.recentChats': 'Recent Chats',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.deleteChat': 'Delete Chat',
    'common.deleteChats': 'Delete Chats',
    'common.deleteSelected': 'Delete Selected',
    'common.noRecentChats': 'No recent chats',
    'common.back': 'Back',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.saving': 'Saving...',
    'common.saveChanges': 'Save Changes',
    'common.sending': 'Sending...',
    
    // Profile
    'profile.changePhoto': 'Change Photo',
    'profile.uploadPhoto': 'Upload Photo',
    'profile.removePhoto': 'Remove Photo',
    'profile.photoUpdated': 'Profile photo updated!',
    'profile.confirmUpload': 'Confirm Upload',
    
    // Settings
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.sessions': 'Sessions',
    'settings.profileInformation': 'Profile Information',
    'settings.contactPerson': 'Contact Person',
    'settings.contactPersonPlaceholder': 'Enter your name',
    'settings.companyName': 'Company Name',
    'settings.companyNamePlaceholder': 'Enter company name',
    'settings.email': 'Email Address',
    'settings.businessType': 'Business Type',
    'settings.selectBusinessType': 'Select business type',
    'settings.consulting': 'Consulting',
    'settings.ecommerce': 'E-commerce',
    'settings.agency': 'Agency',
    'settings.saas': 'SaaS',
    'settings.other': 'Other',
    'settings.businessContext': 'Business Context',
    'settings.businessContextPlaceholder': 'Tell us about your business...',
    'settings.profileUpdated': 'Profile updated successfully',
    'settings.emailNotifications': 'Email Notifications',
    'settings.systemAlerts': 'System Alerts',
    'settings.systemAlertsDesc': 'Receive important system notifications',
    'settings.usageWarnings': 'Usage Warnings',
    'settings.usageWarningsDesc': 'Get notified when approaching usage limits',
    'settings.marketing': 'Marketing Communications',
    'settings.marketingDesc': 'Receive news and product updates',
    'settings.weeklySummary': 'Weekly Summary',
    'settings.weeklySummaryDesc': 'Get a weekly digest of your activity',
    'settings.inAppNotifications': 'In-App Notifications',
    'settings.sounds': 'Notification Sounds',
    'settings.soundsDesc': 'Play sound for notifications',
    'settings.desktopNotifications': 'Desktop Notifications',
    'settings.desktopNotificationsDesc': 'Show browser notifications',
    'settings.settingsSaved': 'Settings saved successfully',
    'settings.dataPersonalization': 'Data & Personalization',
    'settings.allowPersonalization': 'Allow Personalization',
    'settings.allowPersonalizationDesc': 'Use conversation history to personalize responses',
    'settings.storeChatHistory': 'Store Chat History',
    'settings.storeChatHistoryDesc': 'Save conversations for future reference',
    'settings.shareAnonymousData': 'Share Anonymous Usage Data',
    'settings.shareAnonymousDataDesc': 'Help improve AYN with anonymous analytics',
    'settings.dataManagement': 'Data Management',
    'settings.exportData': 'Export Your Data',
    'settings.exportDataDesc': 'Download all your data in JSON format',
    'settings.export': 'Export',
    'settings.dataExported': 'Data exported successfully',
    'settings.deleteChatHistory': 'Delete Chat History',
    'settings.deleteChatHistoryDesc': 'Permanently delete all chat conversations',
    'settings.delete': 'Delete',
    'settings.confirmDeleteHistory': 'Delete All Chat History?',
    'settings.confirmDeleteHistoryDesc': 'This action cannot be undone. All your conversations will be permanently deleted.',
    'settings.chatHistoryDeleted': 'Chat history deleted successfully',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDesc': 'Permanently delete your account and all data',
    'settings.confirmDeleteAccount': 'Delete Your Account?',
    'settings.confirmDeleteAccountDesc': 'This will permanently delete your account, profile, and all associated data. This action cannot be undone.',
    'settings.accountDeleted': 'Account deleted successfully',
    'settings.activeSessions': 'Active Sessions',
    'settings.signOutAll': 'Sign Out All',
    'settings.confirmSignOutAll': 'Sign Out All Devices?',
    'settings.confirmSignOutAllDesc': 'You will be signed out from all devices including this one.',
    'settings.allDevicesSignedOut': 'Signed out from all devices',
    'settings.sessionRevoked': 'Session revoked successfully',
    'settings.noActiveSessions': 'No active sessions',
    'settings.unknownDevice': 'Unknown Device',
    'settings.lastActive': 'Last active',
    'settings.loginCount': 'Logins',
    'settings.trusted': 'Trusted',
    'settings.revoke': 'Revoke',
    'settings.security': 'Security',
    'settings.changePassword': 'Change Password',
    'settings.changePasswordDesc': 'Update your account password',
    'settings.passwordResetEmailSent': 'Password reset email sent! Check your inbox.',
    'settings.searchSettings': 'Search settings...',
    'settings.unsavedChanges': 'Unsaved changes',
    'settings.unsavedChangesTitle': 'Unsaved Changes',
    'settings.unsavedChangesDesc': 'You have unsaved changes. Are you sure you want to leave this page? Your changes will be lost.',
    'settings.stayOnPage': 'Stay on Page',
    'settings.leaveWithoutSaving': 'Leave Without Saving',
    'settings.noResultsFound': 'No settings found matching your search',

    // Session Timeout
    'timeout.title': 'Session Expiring Soon',
    'timeout.description': 'Your session will expire due to inactivity. Click "Stay Logged In" to continue your session.',
    'timeout.secondsRemaining': 'seconds remaining',
    'timeout.stayLoggedIn': 'Stay Logged In',
    'timeout.logoutNow': 'Log Out Now',
    
    // Tutorial
    'tutorial.replay': 'Tutorial',
    
    // Admin Panel
    'admin.panel': 'Admin Panel',
    'admin.title': 'Admin Control Center',
    'admin.subtitle': 'System administration and monitoring',
    'admin.realTime': 'Real-time',
    'admin.refresh': 'Refresh',
    'admin.loading': 'Loading admin panel...',
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.settings': 'Settings',
    'admin.system': 'System',
    'admin.totalUsers': 'Total Users',
    'admin.activeUsers': 'Active Users',
    'admin.pendingRequests': 'Pending Requests',
    'admin.messagesToday': 'Messages Today',
    'admin.systemHealth': 'System Health',
    'admin.resourceUsage': 'Resource Usage',
    'admin.performanceMetrics': 'Performance Metrics',
    'admin.cpuUsage': 'CPU Usage',
    'admin.memoryUsage': 'Memory Usage',
    'admin.diskUsage': 'Disk Usage',
    'admin.avgResponse': 'Avg Response',
    'admin.errorRate': 'Error Rate',
    'admin.database': 'Database',
    'admin.healthy': 'Healthy',
    'admin.apiGateway': 'API Gateway',
    'admin.online': 'Online',
    'admin.webhooks': 'Webhooks',
    'admin.active': 'Active',
    'admin.recentActivity': 'Recent Activity',
    'admin.systemAlerts': 'System Alerts',
    'admin.needsReview': 'Needs review',
    'admin.accessGranted': 'Access granted',
    'admin.pending': 'Pending',
    'admin.systemHealthCheck': 'System health check passed',
    'admin.autoBackup': 'Auto-backup completed',
    'admin.unknownCompany': 'Unknown Company',
    'admin.uptime': 'Uptime',
    
    // User Management
    'admin.userManagement': 'User Management',
    'admin.userManagementDesc': 'Manage user accounts and access permissions',
    'admin.export': 'Export',
    'admin.filtersSearch': 'Filters & Search',
    'admin.searchPlaceholder': 'Search by email, company name or contact person...',
    'admin.filterStatus': 'Filter by status',
    'admin.allUsers': 'All Users',
    'admin.activeOnly': 'Active Only',
    'admin.inactiveOnly': 'Inactive Only',
    'admin.pendingOnly': 'Pending Only',
    'admin.usersCount': 'Users',
    'admin.managePermissions': 'Manage user access and permissions',
    'admin.deniedRevoked': 'Denied/Revoked',
    'admin.expired': 'Expired',
    'admin.noEmail': 'No email',
    'admin.noContact': 'No contact',
    'admin.usage': 'Usage',
    'admin.unlimited': 'Unlimited',
    'admin.created': 'Created',
    'admin.revoke': 'Revoke',
    'admin.view': 'View',
    'admin.noUsersFound': 'No users found',
    'admin.adjustCriteria': 'Try adjusting your search or filter criteria.',
    'admin.accessRevoked': 'Access Revoked',
    'admin.accessRevokedDesc': 'User access has been revoked successfully.',
    'admin.limitsUpdated': 'Limits Updated',
    'admin.limitsUpdatedDesc': 'User limits have been updated successfully.',
    'admin.exportComplete': 'Export Complete',
    'admin.exportCompleteDesc': 'User data has been exported successfully.',
    'admin.editLimit': 'Edit Limit',
    'admin.editBulkLimits': 'Edit Bulk Limits',
    'admin.editUserLimit': 'Edit User Limit',
    'admin.editingLimitsFor': 'Editing limits for',
    'admin.editingLimitFor': 'Editing limit for',
    'admin.currentUsage': 'Current Usage',
    'admin.monthlyLimit': 'Monthly Limit',
    'admin.enterLimit': 'Enter message limit',
    'admin.updateLimit': 'Update Limit',
    'admin.bulkEditLimits': 'Bulk Edit Limits',
    'admin.grantAccess': 'Grant Access',
    'admin.accessRestored': 'Access Restored',
    'admin.accessRestoredDesc': 'User access has been restored successfully',
    'admin.userDetails': 'User Details',
    'admin.bulkActions': 'Bulk Actions',
    'admin.activateSelected': 'Activate Selected',
    'admin.deactivateSelected': 'Deactivate Selected',
    'admin.resetUsageSelected': 'Reset Usage',
    'admin.deleteSelected': 'Delete Selected',
    'admin.configSaved': 'Configuration saved to database',
    'admin.securityAccessControl': 'Security & Access Control',
    'admin.securityAccessControlDesc': 'Advanced security settings and policies',
    
    // System Settings
    'admin.systemConfiguration': 'System Configuration',
    'admin.systemConfigDesc': 'Configure system-wide settings and maintenance options',
    'admin.maintenanceMode': 'Maintenance Mode',
    'admin.maintenanceModeDesc': 'Control system maintenance and user notifications',
    'admin.showMaintenance': 'Show maintenance banner to all users',
    'admin.maintenanceMessage': 'Maintenance Message',
    'admin.maintenancePlaceholder': 'Enter message to display to users...',
    'admin.startTime': 'Start Time (optional)',
    'admin.endTime': 'End Time (optional)',
    'admin.preview': 'Preview',
    'admin.defaultUserSettings': 'Default User Settings',
    'admin.defaultUserSettingsDesc': 'System-wide defaults for new users',
    'admin.defaultMonthlyLimit': 'Default Monthly Limit',
    'admin.defaultMonthlyLimitDesc': 'Default message limit for new users (0 = unlimited)',
    'admin.autoApprove': 'Auto-approve New Requests',
    'admin.autoApproveDesc': 'Automatically approve new access requests',
    'admin.autoApproveRequests': 'Auto-approve New Requests',
    'admin.autoApproveRequestsDesc': 'Automatically approve new access requests',
    'admin.notificationEmailPlaceholder': 'admin@company.com',
    'admin.notificationEmail': 'Notification Email',
    'admin.notificationEmailDesc': 'Email for system notifications and alerts',
    'admin.sessionTimeout': 'Session Timeout (hours)',
    'admin.securityAccess': 'Security & Access Control',
    'admin.securityAccessDesc': 'Advanced security settings and policies',
    'admin.requireApproval': 'Require Admin Approval',
    'admin.requireApprovalDesc': 'All new users require manual approval',
    'admin.requireAdminApproval': 'Require Admin Approval',
    'admin.requireAdminApprovalDesc': 'All new users require manual approval',
    'admin.enableAuditLogging': 'Enable Audit Logging',
    'admin.enableAuditLoggingDesc': 'Log all administrative actions',
    'admin.rateLimitPerMinute': 'Rate Limit (per minute)',
    'admin.rateLimitPerMinuteDesc': 'Maximum requests per minute per user',
    'admin.maxConcurrentSessions': 'Max Concurrent Sessions',
    'admin.maxConcurrentSessionsDesc': 'Maximum simultaneous sessions per user',
    'admin.createDatabaseBackup': 'Create Database Backup',
    'admin.clearSystemCache': 'Clear System Cache',
    'admin.systemMaintenance': 'System Maintenance',
    'admin.systemMaintenanceDesc': 'Perform system maintenance tasks',
    'admin.createBackup': 'Create Database Backup',
    'admin.clearCache': 'Clear System Cache',
    'admin.runHealthCheck': 'Run Health Check',
    'admin.featureToggles': 'Feature Toggles & Experimental Features',
    'admin.featureTogglesDesc': 'Enable or disable system features',
    'admin.realTimeAnalytics': 'Real-time Analytics',
    'admin.realTimeAnalyticsDesc': 'Live usage monitoring',
    'admin.advancedFiltering': 'Advanced User Filtering',
    'admin.advancedFilteringDesc': 'Enhanced search capabilities',
    'admin.advancedUserFiltering': 'Advanced User Filtering',
    'admin.advancedUserFilteringDesc': 'Enhanced search capabilities',
    'admin.apiRateLimiting': 'API Rate Limiting',
    'admin.apiRateLimitingDesc': 'Automatic throttling',
    'admin.bulkOperations': 'Bulk Operations',
    'admin.bulkOperationsDesc': 'Multi-user actions',
    'admin.apiRateLimit': 'API Rate Limiting',
    'admin.apiRateLimitDesc': 'Automatic throttling',
    'admin.securityAlerts': 'Security Alerts',
    'admin.securityAlertsDesc': 'Instant notifications',
    'admin.maintenanceBanner': 'Maintenance Mode',
    'admin.maintenanceBannerDesc': 'System maintenance banner',
    'admin.systemInformation': 'System Information',
    'admin.systemVersion': 'System Version',
    'admin.latestStable': 'Latest stable',
    'admin.databaseVersion': 'Database Version',
    'admin.supabaseHosted': 'Supabase hosted',
    'admin.lastUpdated': 'Last Updated',
    'admin.daysAgo': 'days ago',
    'admin.autoUpdatesEnabled': 'Auto-updates enabled',
    
    // System Monitoring
    'admin.systemMonitoring': 'System Monitoring',
    'admin.systemMonitoringDesc': 'Real-time system performance and health monitoring',
    'admin.systemStatus': 'System Status Overview',
    'admin.excellent': 'Excellent',
    'admin.good': 'Good',
    'admin.fair': 'Fair',
    'admin.poor': 'Poor',
    'admin.last30Days': 'Last 30 days',
    'admin.average': 'Average',
    'admin.last24h': 'Last 24h',
    'admin.serverResources': 'Server Resources',
    'admin.serverResourcesDesc': 'Real-time server resource utilization',
    'admin.status': 'Status',
    'admin.normal': 'normal',
    'admin.moderate': 'moderate',
    'admin.warning': 'warning',
    'admin.critical': 'critical',
    'admin.serviceStatus': 'Service Status',
    'admin.serviceStatusDesc': 'Current status of system services',
    'admin.authentication': 'Authentication',
    'admin.cdn': 'CDN',
    'admin.globalEdge': 'Global Edge Network',
    'admin.optimized': 'Optimized',
    'admin.performanceTrends': 'Performance Trends',
    'admin.performanceTrendsDesc': 'System performance over time',
    'admin.requestsToday': 'Requests Today',
    'admin.activeSessions': 'Active Sessions',
    'admin.peakCpu': 'Peak CPU Usage (24h)',
    'admin.peakMemory': 'Peak Memory Usage (24h)',
    'admin.avgResponse24h': 'Avg Response Time (24h)',
    'admin.systemEvents': 'System Events',
    'admin.systemEventsDesc': 'Recent system events and alerts',
    'admin.healthCheckPassed': 'System health check passed',
    'admin.allServicesNormal': 'All services operating normally',
    'admin.minutesAgo': 'minutes ago',
    'admin.autoScaling': 'Auto-scaling triggered',
    'admin.increasedCapacity': 'Increased capacity due to high load',
    'admin.backupCompleted': 'Database backup completed',
    'admin.backupSuccessful': 'Automated backup successful',
    'admin.hourAgo': 'hour ago',
    'admin.hoursAgo': 'hours ago',
    'admin.highMemoryUsage': 'High memory usage detected',
    'admin.memoryThreshold': 'Memory usage above 80% threshold',
    'admin.securityScanCompleted': 'Security scan completed',
    'admin.noVulnerabilities': 'No vulnerabilities detected',
    'admin.quickActions': 'Quick Actions',
    'admin.quickActionsDesc': 'System monitoring and maintenance tools',
    'admin.viewLogs': 'View Full Logs',
    'admin.resourceReport': 'Resource Report',
    'admin.databaseStatus': 'Database Status',
    'admin.securityAudit': 'Security Audit',
    
    // Auth Modal
    'auth.welcomeToAyn': 'Welcome to AYN',
    'auth.signIn': 'Sign In',
    'auth.requestAccess': 'Request Access',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.missingInfo': 'Missing Information',
    'auth.missingInfoDesc': 'Please fill in all required fields.',
    'auth.verifyEmail': 'Verify your email',
    'auth.verifyEmailDesc': 'Confirmation email re-sent. Please verify, then sign in.',
    'auth.verificationError': 'Verification email error',
    'auth.verificationErrorDesc': 'Could not resend email. Please try again.',
    'auth.authError': 'Authentication Error',
    'auth.welcomeBack': 'Welcome back!',
    'auth.welcomeBackDesc': 'You have been successfully logged in.',
    'auth.requestAccessDesc': 'Request access to AYN AI Business Consulting Platform',
    'auth.fullName': 'Full Name',
    'auth.company': 'Company',
    'auth.businessEmail': 'Business Email',
    'auth.phoneNumber': 'Phone Number',
    'auth.createPassword': 'Create a secure password',
    'auth.registrationSuccess': 'Registration Successful!',
    'auth.registrationSuccessDesc': 'Please check your email to verify your account. Your access will be reviewed by our team.',
    'auth.registrationError': 'Registration Error',
    'auth.accessReviewDesc': 'Access will be reviewed and granted by the AYN team within 24 hours',
    
    // Terms Modal
    'terms.welcomeToAynAI': 'Welcome to AYN AI',
    'terms.businessPartner': 'Your AI Business Partner',
    'terms.reviewTerms': 'Welcome! Please take a moment to review our service terms and privacy policy.',
    'terms.howAynWorks': 'How AYN AI Works',
    'terms.aynDescription': 'AYN AI is designed to help you with business insights and strategic thinking. Here\'s what you should know:',
    'terms.aiSuggestions': 'Our AI provides suggestions and recommendations based on available data and patterns',
    'terms.supportDecisions': 'Responses are meant to support your decision-making process, not replace professional judgment',
    'terms.verifyInfo': 'We recommend verifying important information through additional research',
    'terms.marketInsights': 'Market insights are based on historical data and trends, not real-time guarantees',
    'terms.privacyProtection': 'Privacy & Data Protection',
    'terms.secureProcessing': 'Your conversations are processed securely and used to improve our service',
    'terms.noSharing': 'We do not share your personal business information with third parties',
    'terms.encryption': 'Data is stored with industry-standard encryption and security measures',
    'terms.dataDeletion': 'You can request data deletion by contacting our support team',
    'terms.compliance': 'We comply with applicable data protection regulations',
    'terms.bestPractices': 'Best Practices for Success',
    'terms.researchTool': 'Use AYN AI as a powerful research and brainstorming tool',
    'terms.crossReference': 'Cross-reference important suggestions with industry experts',
    'terms.oneInput': 'Consider AI recommendations as one input in your decision-making process',
    'terms.followUp': 'Feel free to ask follow-up questions to explore different perspectives',
    'terms.serviceInfo': 'Service Information',
    'terms.messageLimits': 'Your account includes monthly message limits as specified in your access plan',
    'terms.serviceUpdates': 'Service updates and improvements are made regularly',
    'terms.availability': 'We strive for high availability but cannot guarantee 100% uptime',
    'terms.support': 'Support is available if you encounter any issues',
    'terms.importantNote': 'While AYN AI is a powerful business tool, all final decisions remain yours to make. We recommend using our insights alongside your expertise and, when appropriate, professional consultation for major business decisions.',
    'terms.hasRead': 'I have read and understood the above terms and disclaimer',
    'terms.acceptTerms': 'I accept these terms and agree to use AYN AI at my own risk and discretion',
    'terms.acceptContinue': 'Accept Terms & Continue to AYN AI',
    
    // 404 Page
    'notFound.pageNotFound': 'Page Not Found',
    'notFound.description': 'Oops! It seems like AYN couldn\'t locate the page you\'re looking for. Let\'s get you back to exploring business insights.',
    'notFound.goBack': 'Go Back',
    'notFound.returnHome': 'Return Home',
    'notFound.needHelp': 'Need help? AYN is always ready to assist with your business questions.',
    
    // Tutorial
    'tutorial.welcome.title': 'Welcome to AYN',
    'tutorial.welcome.subtitle': 'Let me show you around and help you get started',
    'tutorial.welcome.startButton': 'Start Tour',
    'tutorial.welcome.skipButton': 'Skip for now',
    'tutorial.steps.eye.title': 'Meet AYN',
    'tutorial.steps.eye.description': 'This is AYN, your AI assistant. Watch how the eye follows your cursor and responds to your messages.',
    'tutorial.steps.eyeEmotions.title': 'AYN\'s Emotions',
    'tutorial.steps.eyeEmotions.description': 'The eye color reflects AYN\'s mood:\n🟢 Green = Happy\n🔵 Blue = Thinking\n🟠 Orange = Excited\n🔴 Red = Frustrated\n🟣 Purple = Curious',
    'tutorial.steps.chatInput.title': 'Start Chatting',
    'tutorial.steps.chatInput.description': 'Type your message here. Your message will fly to AYN and get absorbed!',
    'tutorial.steps.attachment.title': 'Add Files',
    'tutorial.steps.attachment.description': 'Click + to attach files, images, or PDFs. AYN can analyze them for you.',
    'tutorial.steps.suggestions.title': 'Smart Suggestions',
    'tutorial.steps.suggestions.description': 'After AYN responds, click any suggestion bubble for quick follow-up questions.',
    'tutorial.steps.sidebar.title': 'Navigation',
    'tutorial.steps.sidebar.description': 'Access your recent chats, search conversations, and pin favorites.',
    'tutorial.steps.transcript.title': 'Conversation History',
    'tutorial.steps.transcript.description': 'Click here to see your full conversation transcript.',
    'tutorial.steps.profile.title': 'Your Profile',
    'tutorial.steps.profile.description': 'Access settings, change your avatar, switch language, or log out.',
    'tutorial.navigation.next': 'Next',
    'tutorial.navigation.previous': 'Previous',
    'tutorial.navigation.skip': 'Skip Tour',
    'tutorial.navigation.finish': 'Get Started!',
    'tutorial.navigation.stepOf': 'of',
  },
  ar: {
    // Navigation
    'nav.features': 'المميزات',
    'nav.testimonials': 'آراء العملاء',
    'nav.getStarted': 'ابدأ الآن',
    
    // Hero Section
    'hero.title': 'شريك نمو أعمالك',
    'hero.titleHighlight': 'المدعوم بالذكاء الاصطناعي',
    'hero.description': 'احصل على رؤى استراتيجية للأعمال، وأبحاث السوق، وتحسين المبيعات، وتحليل الاتجاهات - كل ذلك من مستشار ذكي واحد.',
    'hero.cta': 'ابدأ الاستشارة مع AYN',
    'hero.joinBusiness': 'انضم إلى أكثر من 10,000 شركة نامية',
    'hero.readyToAnalyze': 'جاهز لتحليل أعمالك',
    'hero.aiConsultantQuote': 'يمكنني مساعدتك في أبحاث السوق، والتحليل التنافسي، وتحسين المبيعات، والتخطيط الاستراتيجي. بماذا تود أن نبدأ؟',
    
    // Features Section
    'features.title': 'ذكاء أعمال شامل',
    'features.subtitle': 'وكيل ذكي واحد بقدرات متخصصة متعددة لتسريع نمو أعمالك',
    'features.marketResearch.title': 'أبحاث السوق',
    'features.marketResearch.description': 'احصل على رؤى استراتيجية للأعمال مع تحليل شامل للسوق والذكاء التنافسي.',
    'features.salesOptimization.title': 'تحسين المبيعات',
    'features.salesOptimization.description': 'حسن قمع المبيعات ومعدلات التحويل باستخدام توصيات مدفوعة بالبيانات.',
    'features.trendAnalysis.title': 'تحليل الاتجاهات',
    'features.trendAnalysis.description': 'حلل اتجاهات السوق وحدد الفرص الناشئة قبل منافسيك.',
    'features.strategicPlanning.title': 'التخطيط الاستراتيجي',
    'features.strategicPlanning.description': 'استشارات أعمال شاملة وتخطيط استراتيجي مدعوم بالذكاء الاصطناعي المتقدم.',
    
    // Testimonials Section
    'testimonials.title': 'موثوق به من قادة الصناعة',
    'testimonials.subtitle': 'اكتشف كيف يحول AYN الأعمال حول العالم',
    'testimonials.sarah.quote': 'لقد غير AYN استراتيجية أعمالنا. كانت الرؤى ثورية.',
    'testimonials.marcus.quote': 'قدرات تحليل السوق مفصلة بشكل لا يصدق وقابلة للتنفيذ.',
    'testimonials.emma.quote': 'ساعدتنا توقعات اتجاهات AYN في تغيير استراتيجيتنا في الوقت المثالي.',
    
    // Footer
    'footer.copyright': '© 2024 AYN للاستشارات التجارية بالذكاء الاصطناعي. جميع الحقوق محفوظة.',
    
    // Mode names in Modern Standard Arabic
    'modes.general': 'عام',
    'modes.nenMode': 'وضع نين',
    'modes.researchPro': 'بحث متقدم',
    'modes.pdfAnalyst': 'محلل المستندات',
    'modes.visionLab': 'مختبر الرؤية',
    'modes.civilEngineering': 'الهندسة المدنية',
    
    // Header elements in Arabic
    'header.aynBusinessConsole': 'منصة عين للأعمال',
    'header.chat': 'محادثة',
    'header.admin': 'المدير',
    
    // Dashboard
    'dashboard.loading': 'جاري تحميل AYN...',
    'dashboard.chatLoaded': 'تم تحميل المحادثة',
    'dashboard.loadedConversation': 'تم تحميل المحادثة',
    'dashboard.newChatDesc': 'يمكنك الآن بدء محادثة جديدة مع AYN.',
    'dashboard.chatsDeleted': 'تم حذف المحادثات',
    'dashboard.successfullyDeleted': 'تم الحذف بنجاح',
    'dashboard.conversations': 'محادثة (محادثات)',
    'dashboard.templates.marketAnalysis': 'تحليل السوق',
    'dashboard.templates.marketAnalysisPrompt': 'حلل الاتجاهات الحالية للسوق والفرص في صناعتي',
    'dashboard.templates.salesFunnel': 'مراجعة قمع المبيعات',
    'dashboard.templates.salesFunnelPrompt': 'راجع عملية المبيعات الخاصة بي وحدد عقد التحويل',
    'dashboard.templates.competitorResearch': 'بحث المنافسين',
    'dashboard.templates.competitorResearchPrompt': 'ابحث عن منافسيي الرئيسيين واستراتيجياتهم',
    'dashboard.templates.growthStrategy': 'استراتيجية النمو',
    'dashboard.templates.growthStrategyPrompt': 'طور استراتيجية نمو شاملة لتوسيع أعمالي',
    
    // Mode-specific placeholders in Modern Standard Arabic (stored as JSON strings)
    'placeholders.General': '["اسأل عن استراتيجية عملك", "كيف يمكنني تحسين عملياتك؟", "ما التحدي التجاري الذي تواجهه؟"]',
    'placeholders.Nen Mode ⚡': '["احصل على رؤى استراتيجية متخصصة", "اطلب تحليلاً شاملاً", "تحتاج استشارة متخصصة؟"]',
    'placeholders.Research Pro': '["ما اتجاهات السوق التي يجب بحثها؟", "ابحث عن أحدث بيانات الصناعة", "أي منافس يجب تحليله؟"]',
    'placeholders.PDF Analyst': '["ارفع مستند عملك", "دعني أراجع ملفاتك", "ارفع PDF للتحليل"]',
    'placeholders.Vision Lab': '["ارفع صورة للتحليل", "حلل المخططات والصور", "شارك المحتوى المرئي"]',
    
    // Legacy placeholders (keeping for backward compatibility)
    'dashboard.placeholders.askAyn': 'اسأل AYN أي شيء عن أعمالك',
    'dashboard.placeholders.increaseRevenue': 'كيف يمكنني زيادة إيراداتي؟',
    'dashboard.placeholders.marketTrends': 'ما هي أحدث اتجاهات السوق؟',
    'dashboard.placeholders.competitionStrategy': 'حلل استراتيجية منافستي',
    'dashboard.placeholders.optimizeSales': 'كيف أحسن قمع المبيعات؟',
    'dashboard.placeholders.growthOpportunities': 'ما هي فرص النمو الموجودة؟',
    'dashboard.placeholders.pricingStrategy': 'ساعدني في استراتيجية التسعير',
    'dashboard.placeholders.targetMarket': 'ابحث عن السوق المستهدف',
    
    // Auth & Access
    'auth.termsRequired': 'الشروط مطلوبة',
    'auth.termsRequiredDesc': 'يرجى قبول الشروط والأحكام قبل استخدام AYN AI.',
    'auth.accessRequired': 'الوصول مطلوب',
    'auth.accessRequiredDesc': 'تحتاج إلى وصول نشط لاستخدام AYN. يرجى الاتصال بفريقنا.',
    'auth.welcomeTitle': 'مرحباً بك في AYN!',
    'auth.welcomeDesc': 'يمكنك الآن البدء في استخدام خدمات الاستشارات التجارية لـ AYN AI.',
    
    // Errors & Messages
    'error.usageLimit': 'تم الوصول لحد الاستخدام',
    'error.usageLimitDesc': 'لقد وصلت إلى حد الرسائل الشهرية. يرجى الاتصال بالدعم أو انتظار إعادة تعيين الشهر القادم.',
    'error.systemError': 'خطأ في النظام',
    'error.systemErrorDesc': 'غير قادر على معالجة طلبك. يرجى المحاولة مرة أخرى.',
    
    // Common
    'common.signOut': 'تسجيل الخروج',
    'common.settings': 'الإعدادات',
    'common.admin': 'المشرف',
    'common.chat': 'المحادثة',
    'common.language': 'اللغة',
    'common.noConversations': 'لا توجد محادثات بعد. ابدأ المحادثة مع AYN!',
    'common.newChat': 'محادثة جديدة',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.thinking': 'يفكر...',
    'common.user': 'المستخدم',
    'common.quickStart': 'البداية السريعة',
    'common.recentChats': 'المحادثات الأخيرة',
    'common.select': 'تحديد',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.deleteChat': 'حذف محادثة',
    'common.deleteChats': 'حذف محادثات',
    'common.deleteSelected': 'حذف المحدد',
    'common.noRecentChats': 'لا توجد محادثات حديثة',
    'common.back': 'رجوع',
    'common.success': 'نجاح',
    'common.error': 'خطأ',
    'common.saving': 'جاري الحفظ...',
    'common.saveChanges': 'حفظ التغييرات',
    'common.sending': 'جاري الإرسال...',
    
    // Profile
    'profile.changePhoto': 'تغيير الصورة',
    'profile.uploadPhoto': 'رفع صورة',
    'profile.removePhoto': 'إزالة الصورة',
    'profile.photoUpdated': 'تم تحديث صورة الملف الشخصي!',
    'profile.confirmUpload': 'تأكيد الرفع',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.account': 'الحساب',
    'settings.notifications': 'الإشعارات',
    'settings.privacy': 'الخصوصية',
    'settings.sessions': 'الجلسات',
    'settings.profileInformation': 'معلومات الملف الشخصي',
    'settings.contactPerson': 'اسم جهة الاتصال',
    'settings.contactPersonPlaceholder': 'أدخل اسمك',
    'settings.companyName': 'اسم الشركة',
    'settings.companyNamePlaceholder': 'أدخل اسم الشركة',
    'settings.email': 'البريد الإلكتروني',
    'settings.businessType': 'نوع العمل',
    'settings.selectBusinessType': 'اختر نوع العمل',
    'settings.consulting': 'استشارات',
    'settings.ecommerce': 'تجارة إلكترونية',
    'settings.agency': 'وكالة',
    'settings.saas': 'خدمة سحابية',
    'settings.other': 'أخرى',
    'settings.businessContext': 'سياق العمل',
    'settings.businessContextPlaceholder': 'أخبرنا عن عملك...',
    'settings.profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
    'settings.emailNotifications': 'إشعارات البريد الإلكتروني',
    'settings.systemAlerts': 'تنبيهات النظام',
    'settings.systemAlertsDesc': 'استلم إشعارات النظام المهمة',
    'settings.usageWarnings': 'تحذيرات الاستخدام',
    'settings.usageWarningsDesc': 'احصل على إشعار عند الاقتراب من حدود الاستخدام',
    'settings.marketing': 'الاتصالات التسويقية',
    'settings.marketingDesc': 'استلم الأخبار وتحديثات المنتج',
    'settings.weeklySummary': 'ملخص أسبوعي',
    'settings.weeklySummaryDesc': 'احصل على ملخص أسبوعي لنشاطك',
    'settings.inAppNotifications': 'الإشعارات داخل التطبيق',
    'settings.sounds': 'أصوات الإشعارات',
    'settings.soundsDesc': 'تشغيل صوت للإشعارات',
    'settings.desktopNotifications': 'إشعارات سطح المكتب',
    'settings.desktopNotificationsDesc': 'عرض إشعارات المتصفح',
    'settings.settingsSaved': 'تم حفظ الإعدادات بنجاح',
    'settings.dataPersonalization': 'البيانات والتخصيص',
    'settings.allowPersonalization': 'السماح بالتخصيص',
    'settings.allowPersonalizationDesc': 'استخدام سجل المحادثات لتخصيص الردود',
    'settings.storeChatHistory': 'حفظ سجل المحادثات',
    'settings.storeChatHistoryDesc': 'حفظ المحادثات للرجوع إليها لاحقاً',
    'settings.shareAnonymousData': 'مشاركة بيانات الاستخدام المجهولة',
    'settings.shareAnonymousDataDesc': 'ساعد في تحسين AYN بتحليلات مجهولة',
    'settings.dataManagement': 'إدارة البيانات',
    'settings.exportData': 'تصدير بياناتك',
    'settings.exportDataDesc': 'تنزيل جميع بياناتك بصيغة JSON',
    'settings.export': 'تصدير',
    'settings.dataExported': 'تم تصدير البيانات بنجاح',
    'settings.deleteChatHistory': 'حذف سجل المحادثات',
    'settings.deleteChatHistoryDesc': 'حذف جميع المحادثات نهائياً',
    'settings.delete': 'حذف',
    'settings.confirmDeleteHistory': 'حذف جميع سجل المحادثات؟',
    'settings.confirmDeleteHistoryDesc': 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع محادثاتك نهائياً.',
    'settings.chatHistoryDeleted': 'تم حذف سجل المحادثات بنجاح',
    'settings.deleteAccount': 'حذف الحساب',
    'settings.deleteAccountDesc': 'حذف حسابك وجميع البيانات نهائياً',
    'settings.confirmDeleteAccount': 'حذف حسابك؟',
    'settings.confirmDeleteAccountDesc': 'سيتم حذف حسابك وملفك الشخصي وجميع البيانات المرتبطة به نهائياً. لا يمكن التراجع عن هذا الإجراء.',
    'settings.accountDeleted': 'تم حذف الحساب بنجاح',
    'settings.activeSessions': 'الجلسات النشطة',
    'settings.signOutAll': 'تسجيل الخروج من الكل',
    'settings.confirmSignOutAll': 'تسجيل الخروج من جميع الأجهزة؟',
    'settings.confirmSignOutAllDesc': 'سيتم تسجيل خروجك من جميع الأجهزة بما في ذلك هذا الجهاز.',
    'settings.allDevicesSignedOut': 'تم تسجيل الخروج من جميع الأجهزة',
    'settings.sessionRevoked': 'تم إلغاء الجلسة بنجاح',
    'settings.noActiveSessions': 'لا توجد جلسات نشطة',
    'settings.unknownDevice': 'جهاز غير معروف',
    'settings.lastActive': 'آخر نشاط',
    'settings.loginCount': 'عدد تسجيلات الدخول',
    'settings.trusted': 'موثوق',
    'settings.revoke': 'إلغاء',
    'settings.security': 'الأمان',
    'settings.changePassword': 'تغيير كلمة المرور',
    'settings.changePasswordDesc': 'تحديث كلمة مرور حسابك',
    'settings.passwordResetEmailSent': 'تم إرسال بريد إعادة تعيين كلمة المرور! تحقق من بريدك الوارد.',
    'settings.searchSettings': 'بحث في الإعدادات...',
    'settings.unsavedChanges': 'تغييرات غير محفوظة',
    'settings.unsavedChangesTitle': 'تغييرات غير محفوظة',
    'settings.unsavedChangesDesc': 'لديك تغييرات غير محفوظة. هل أنت متأكد من أنك تريد مغادرة هذه الصفحة؟ ستفقد التغييرات.',
    'settings.stayOnPage': 'البقاء في الصفحة',
    'settings.leaveWithoutSaving': 'المغادرة دون حفظ',
    'settings.noResultsFound': 'لم يتم العثور على إعدادات مطابقة لبحثك',
    
    // Session Timeout
    'timeout.title': 'انتهاء الجلسة قريباً',
    'timeout.description': 'ستنتهي جلستك بسبب عدم النشاط. انقر على "البقاء متصلاً" لمتابعة جلستك.',
    'timeout.secondsRemaining': 'ثانية متبقية',
    'timeout.stayLoggedIn': 'البقاء متصلاً',
    'timeout.logoutNow': 'تسجيل الخروج الآن',
    
    // Tutorial
    'tutorial.replay': 'الدليل التعليمي',
    
    // Admin Panel
    'admin.panel': 'لوحة الإدارة',
    'admin.title': 'مركز التحكم الإداري',
    'admin.subtitle': 'إدارة ومراقبة النظام',
    'admin.realTime': 'الوقت الحقيقي',
    'admin.refresh': 'تحديث',
    'admin.loading': 'جاري تحميل لوحة الإدارة...',
    'admin.dashboard': 'لوحة التحكم',
    'admin.users': 'المستخدمون',
    'admin.settings': 'الإعدادات',
    'admin.system': 'النظام',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.activeUsers': 'المستخدمون النشطون',
    'admin.pendingRequests': 'الطلبات المعلقة',
    'admin.messagesToday': 'رسائل اليوم',
    'admin.systemHealth': 'صحة النظام',
    'admin.resourceUsage': 'استخدام الموارد',
    'admin.performanceMetrics': 'مقاييس الأداء',
    'admin.cpuUsage': 'استخدام المعالج',
    'admin.memoryUsage': 'استخدام الذاكرة',
    'admin.diskUsage': 'استخدام القرص',
    'admin.avgResponse': 'متوسط الاستجابة',
    'admin.errorRate': 'معدل الخطأ',
    'admin.database': 'قاعدة البيانات',
    'admin.healthy': 'سليم',
    'admin.apiGateway': 'بوابة API',
    'admin.online': 'متصل',
    'admin.webhooks': 'الـ Webhooks',
    'admin.active': 'نشط',
    'admin.recentActivity': 'النشاط الحديث',
    'admin.systemAlerts': 'تنبيهات النظام',
    'admin.needsReview': 'يحتاج مراجعة',
    'admin.accessGranted': 'تم منح الوصول',
    'admin.pending': 'معلق',
    'admin.systemHealthCheck': 'تم اجتياز فحص صحة النظام',
    'admin.autoBackup': 'تم الانتهاء من النسخ الاحتياطي التلقائي',
    'admin.unknownCompany': 'شركة غير معروفة',
    'admin.uptime': 'وقت التشغيل',
    
    // User Management
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.userManagementDesc': 'إدارة حسابات المستخدمين وصلاحيات الوصول',
    'admin.export': 'تصدير',
    'admin.filtersSearch': 'المرشحات والبحث',
    'admin.searchPlaceholder': 'البحث بالبريد الإلكتروني أو اسم الشركة أو جهة الاتصال...',
    'admin.filterStatus': 'تصفية حسب الحالة',
    'admin.allUsers': 'جميع المستخدمين',
    'admin.activeOnly': 'النشطون فقط',
    'admin.inactiveOnly': 'غير النشطين فقط',
    'admin.pendingOnly': 'المعلقون فقط',
    'admin.usersCount': 'المستخدمون',
    'admin.managePermissions': 'إدارة وصول المستخدمين والأذونات',
    'admin.deniedRevoked': 'مرفوض/ملغى',
    'admin.expired': 'منتهي الصلاحية',
    'admin.noEmail': 'لا يوجد بريد إلكتروني',
    'admin.noContact': 'لا يوجد جهة اتصال',
    'admin.usage': 'الاستخدام',
    'admin.unlimited': 'غير محدود',
    'admin.created': 'تم الإنشاء',
    'admin.revoke': 'إلغاء',
    'admin.view': 'عرض',
    'admin.noUsersFound': 'لم يتم العثور على مستخدمين',
    'admin.adjustCriteria': 'حاول تعديل معايير البحث أو التصفية.',
    'admin.accessRevoked': 'تم إلغاء الوصول',
    'admin.accessRevokedDesc': 'تم إلغاء وصول المستخدم بنجاح.',
    'admin.limitsUpdated': 'تم تحديث الحدود',
    'admin.limitsUpdatedDesc': 'تم تحديث حدود المستخدم بنجاح.',
    'admin.exportComplete': 'اكتمل التصدير',
    'admin.exportCompleteDesc': 'تم تصدير بيانات المستخدم بنجاح.',
    'admin.editLimit': 'تعديل الحد',
    'admin.editBulkLimits': 'تعديل الحدود بالجملة',
    'admin.editUserLimit': 'تعديل حد المستخدم',
    'admin.editingLimitsFor': 'تعديل الحدود لـ',
    'admin.editingLimitFor': 'تعديل الحد لـ',
    'admin.currentUsage': 'الاستخدام الحالي',
    'admin.monthlyLimit': 'الحد الشهري',
    'admin.enterLimit': 'أدخل حد الرسائل',
    'admin.updateLimit': 'تحديث الحد',
    'admin.bulkEditLimits': 'تعديل الحدود بالجملة',
    'admin.grantAccess': 'منح الوصول',
    'admin.accessRestored': 'تم استعادة الوصول',
    'admin.accessRestoredDesc': 'تم استعادة وصول المستخدم بنجاح',
    'admin.userDetails': 'تفاصيل المستخدم',
    'admin.bulkActions': 'إجراءات جماعية',
    'admin.activateSelected': 'تفعيل المحدد',
    'admin.deactivateSelected': 'إلغاء تفعيل المحدد',
    'admin.resetUsageSelected': 'إعادة تعيين الاستخدام',
    'admin.deleteSelected': 'حذف المحدد',
    'admin.configSaved': 'تم حفظ التكوين في قاعدة البيانات',
    'admin.securityAccessControl': 'الأمان والتحكم في الوصول',
    'admin.securityAccessControlDesc': 'إعدادات الأمان المتقدمة والسياسات',
    
    // System Settings
    'admin.systemConfiguration': 'تكوين النظام',
    'admin.systemConfigDesc': 'تكوين إعدادات النظام وخيارات الصيانة',
    'admin.maintenanceMode': 'وضع الصيانة',
    'admin.maintenanceModeDesc': 'التحكم في صيانة النظام وإشعارات المستخدمين',
    'admin.showMaintenance': 'إظهار شعار الصيانة لجميع المستخدمين',
    'admin.maintenanceMessage': 'رسالة الصيانة',
    'admin.maintenancePlaceholder': 'أدخل الرسالة لعرضها للمستخدمين...',
    'admin.startTime': 'وقت البداية (اختياري)',
    'admin.endTime': 'وقت النهاية (اختياري)',
    'admin.preview': 'معاينة',
    'admin.defaultUserSettings': 'إعدادات المستخدم الافتراضية',
    'admin.defaultUserSettingsDesc': 'الإعدادات الافتراضية على مستوى النظام للمستخدمين الجدد',
    'admin.defaultMonthlyLimit': 'الحد الشهري الافتراضي',
    'admin.defaultMonthlyLimitDesc': 'حد الرسائل الافتراضي للمستخدمين الجدد (0 = غير محدود)',
    'admin.autoApprove': 'الموافقة التلقائية على الطلبات الجديدة',
    'admin.autoApproveDesc': 'الموافقة تلقائياً على طلبات الوصول الجديدة',
    'admin.autoApproveRequests': 'الموافقة التلقائية على الطلبات الجديدة',
    'admin.autoApproveRequestsDesc': 'الموافقة تلقائياً على طلبات الوصول الجديدة',
    'admin.notificationEmailPlaceholder': 'admin@company.com',
    'admin.notificationEmail': 'بريد الإشعارات',
    'admin.notificationEmailDesc': 'البريد الإلكتروني لإشعارات النظام والتنبيهات',
    'admin.sessionTimeout': 'مهلة الجلسة (ساعات)',
    'admin.securityAccess': 'الأمان والتحكم في الوصول',
    'admin.securityAccessDesc': 'إعدادات الأمان المتقدمة والسياسات',
    'admin.requireApproval': 'يتطلب موافقة المشرف',
    'admin.requireApprovalDesc': 'جميع المستخدمين الجدد يتطلبون موافقة يدوية',
    'admin.requireAdminApproval': 'يتطلب موافقة المشرف',
    'admin.requireAdminApprovalDesc': 'جميع المستخدمين الجدد يتطلبون موافقة يدوية',
    'admin.enableAuditLogging': 'تمكين تسجيل التدقيق',
    'admin.enableAuditLoggingDesc': 'تسجيل جميع الإجراءات الإدارية',
    'admin.rateLimitPerMinute': 'حد المعدل (في الدقيقة)',
    'admin.rateLimitPerMinuteDesc': 'الحد الأقصى للطلبات في الدقيقة لكل مستخدم',
    'admin.maxConcurrentSessions': 'الحد الأقصى للجلسات المتزامنة',
    'admin.maxConcurrentSessionsDesc': 'الحد الأقصى للجلسات المتزامنة لكل مستخدم',
    'admin.createDatabaseBackup': 'إنشاء نسخة احتياطية لقاعدة البيانات',
    'admin.clearSystemCache': 'مسح ذاكرة التخزين المؤقت للنظام',
    'admin.systemMaintenance': 'صيانة النظام',
    'admin.systemMaintenanceDesc': 'تنفيذ مهام صيانة النظام',
    'admin.createBackup': 'إنشاء نسخة احتياطية لقاعدة البيانات',
    'admin.clearCache': 'مسح ذاكرة التخزين المؤقت للنظام',
    'admin.runHealthCheck': 'تشغيل فحص الصحة',
    'admin.featureToggles': 'مفاتيح الميزات والميزات التجريبية',
    'admin.featureTogglesDesc': 'تمكين أو تعطيل ميزات النظام',
    'admin.realTimeAnalytics': 'التحليلات في الوقت الفعلي',
    'admin.realTimeAnalyticsDesc': 'مراقبة الاستخدام المباشر',
    'admin.advancedFiltering': 'التصفية المتقدمة للمستخدمين',
    'admin.advancedFilteringDesc': 'قدرات بحث محسّنة',
    'admin.advancedUserFiltering': 'التصفية المتقدمة للمستخدمين',
    'admin.advancedUserFilteringDesc': 'قدرات بحث محسّنة',
    'admin.apiRateLimiting': 'حد معدل API',
    'admin.apiRateLimitingDesc': 'التحكم التلقائي في التدفق',
    'admin.bulkOperations': 'العمليات المجمعة',
    'admin.bulkOperationsDesc': 'إجراءات متعددة المستخدمين',
    'admin.apiRateLimit': 'حد معدل API',
    'admin.apiRateLimitDesc': 'التحكم التلقائي في التدفق',
    'admin.securityAlerts': 'تنبيهات الأمان',
    'admin.securityAlertsDesc': 'إشعارات فورية',
    'admin.maintenanceBanner': 'وضع الصيانة',
    'admin.maintenanceBannerDesc': 'شعار صيانة النظام',
    'admin.systemInformation': 'معلومات النظام',
    'admin.systemVersion': 'إصدار النظام',
    'admin.latestStable': 'أحدث إصدار مستقر',
    'admin.databaseVersion': 'إصدار قاعدة البيانات',
    'admin.supabaseHosted': 'مستضاف على Supabase',
    'admin.lastUpdated': 'آخر تحديث',
    'admin.daysAgo': 'منذ أيام',
    'admin.twoDaysAgo': 'منذ يومين',
    'admin.autoUpdatesEnabled': 'التحديثات التلقائية مفعلة',
    
    // Email Campaigns
    'admin.emailCampaigns': 'حملات البريد الإلكتروني',
    'admin.emailCampaignsDesc': 'إنشاء وإدارة حملات البريد الإلكتروني المجمعة',
    'admin.recipientGroups': 'مجموعات المستلمين',
    'admin.newCampaign': 'حملة جديدة',
    'admin.totalCampaigns': 'إجمالي الحملات',
    'admin.activeCampaigns': 'الحملات النشطة',
    'admin.totalRecipients': 'إجمالي المستلمين',
    'admin.emailsSent': 'الإيميلات المرسلة',
    'admin.manageCampaigns': 'إدارة حملات التسويق والتواصل عبر البريد الإلكتروني',
    'admin.loadingCampaigns': 'جاري تحميل حملات البريد الإلكتروني...',
    'admin.recipients': 'المستلمون',
    'admin.sent': 'مرسل',
    'admin.createEmailCampaign': 'إنشاء حملة بريد إلكتروني',
    'admin.setupNewCampaign': 'إعداد حملة بريد إلكتروني جديدة للمستخدمين',
    'admin.campaignName': 'اسم الحملة',
    'admin.campaignType': 'نوع الحملة',
    'admin.marketing': 'التسويق',
    'admin.newsletter': 'النشرة الإخبارية',
    'admin.onboarding': 'التأهيل',
    'admin.notification': 'الإشعارات',
    'admin.announcement': 'الإعلانات',
    'admin.emailSubject': 'موضوع البريد الإلكتروني',
    'admin.emailContent': 'محتوى البريد الإلكتروني',
    'admin.writeEmailContent': 'اكتب محتوى البريد الإلكتروني هنا...',
    'admin.recipientGroupsSelect': 'مجموعات المستلمين',
    'admin.schedule': 'الجدولة (اختياري)',
    'admin.cancel': 'إلغاء',
    'admin.saveDraft': 'حفظ كمسودة',
    'admin.sendCampaign': 'إرسال الحملة',
    'admin.scheduleCampaign': 'جدولة الحملة',
    'admin.campaignDetails': 'تفاصيل الحملة وإحصائياتها',
    'admin.subject': 'الموضوع',
    'admin.content': 'المحتوى',
    'admin.draft': 'مسودة',
    'admin.scheduled': 'مجدولة',
    'admin.sending': 'جاري الإرسال',
    'admin.completed': 'مكتملة',
    'admin.paused': 'متوقفة',
    'admin.monthlyNewsletter': 'النشرة الشهرية',
    'admin.monthlyUpdates': 'تحديثك الشهري من AYN',
    'admin.error': 'خطأ',
    'admin.fetchCampaignsError': 'فشل في جلب حملات البريد الإلكتروني',
    'admin.fetchGroupsError': 'فشل في جلب مجموعات المستلمين',
    
    // System Monitoring
    'admin.systemMonitoring': 'مراقبة النظام',
    'admin.systemMonitoringDesc': 'مراقبة أداء وصحة النظام في الوقت الفعلي',
    'admin.systemStatus': 'نظرة عامة على حالة النظام',
    'admin.excellent': 'ممتاز',
    'admin.good': 'جيد',
    'admin.fair': 'مقبول',
    'admin.poor': 'ضعيف',
    'admin.last30Days': 'آخر 30 يوماً',
    'admin.average': 'متوسط',
    'admin.last24h': 'آخر 24 ساعة',
    'admin.serverResources': 'موارد الخادم',
    'admin.serverResourcesDesc': 'استخدام موارد الخادم في الوقت الفعلي',
    'admin.status': 'الحالة',
    'admin.normal': 'عادي',
    'admin.moderate': 'متوسط',
    'admin.warning': 'تحذير',
    'admin.critical': 'حرج',
    'admin.serviceStatus': 'حالة الخدمات',
    'admin.serviceStatusDesc': 'الحالة الحالية لخدمات النظام',
    'admin.authentication': 'المصادقة',
    'admin.cdn': 'شبكة CDN',
    'admin.globalEdge': 'الشبكة العالمية الطرفية',
    'admin.optimized': 'محسّن',
    'admin.performanceTrends': 'اتجاهات الأداء',
    'admin.performanceTrendsDesc': 'أداء النظام عبر الوقت',
    'admin.requestsToday': 'الطلبات اليوم',
    'admin.activeSessions': 'الجلسات النشطة',
    'admin.peakCpu': 'ذروة استخدام المعالج (24 ساعة)',
    'admin.peakMemory': 'ذروة استخدام الذاكرة (24 ساعة)',
    'admin.avgResponse24h': 'متوسط وقت الاستجابة (24 ساعة)',
    'admin.systemEvents': 'أحداث النظام',
    'admin.systemEventsDesc': 'أحداث النظام والتنبيهات الحديثة',
    'admin.healthCheckPassed': 'تم اجتياز فحص صحة النظام',
    'admin.allServicesNormal': 'جميع الخدمات تعمل بشكل طبيعي',
    'admin.minutesAgo': 'منذ دقائق',
    'admin.autoScaling': 'تم تفعيل التوسع التلقائي',
    'admin.increasedCapacity': 'زيادة السعة بسبب الحمولة العالية',
    'admin.backupCompleted': 'اكتملت النسخة الاحتياطية لقاعدة البيانات',
    'admin.backupSuccessful': 'النسخ الاحتياطي التلقائي ناجح',
    'admin.hourAgo': 'منذ ساعة',
    'admin.hoursAgo': 'منذ ساعات',
    'admin.highMemoryUsage': 'تم اكتشاف استخدام عالي للذاكرة',
    'admin.memoryThreshold': 'استخدام الذاكرة فوق عتبة 80%',
    'admin.securityScanCompleted': 'اكتمل فحص الأمان',
    'admin.noVulnerabilities': 'لم يتم اكتشاف ثغرات أمنية',
    'admin.quickActions': 'الإجراءات السريعة',
    'admin.quickActionsDesc': 'أدوات مراقبة وصيانة النظام',
    'admin.viewLogs': 'عرض جميع السجلات',
    'admin.resourceReport': 'تقرير الموارد',
    'admin.databaseStatus': 'حالة قاعدة البيانات',
    'admin.securityAudit': 'تدقيق الأمان',
    
    // Auth Modal
    'auth.welcomeToAyn': 'مرحباً بك في AYN',
    'auth.signIn': 'تسجيل الدخول',
    'auth.requestAccess': 'طلب الوصول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.enterEmail': 'أدخل بريدك الإلكتروني',
    'auth.enterPassword': 'أدخل كلمة المرور',
    'auth.missingInfo': 'معلومات مفقودة',
    'auth.missingInfoDesc': 'يرجى ملء جميع الحقول المطلوبة.',
    'auth.verifyEmail': 'تحقق من بريدك الإلكتروني',
    'auth.verifyEmailDesc': 'تم إعادة إرسال بريد التأكيد. يرجى التحقق، ثم تسجيل الدخول.',
    'auth.verificationError': 'خطأ في بريد التحقق',
    'auth.verificationErrorDesc': 'لا يمكن إعادة إرسال البريد الإلكتروني. يرجى المحاولة مرة أخرى.',
    'auth.authError': 'خطأ في المصادقة',
    'auth.welcomeBack': 'مرحباً بعودتك!',
    'auth.welcomeBackDesc': 'تم تسجيل دخولك بنجاح.',
    'auth.requestAccessDesc': 'طلب الوصول إلى منصة الاستشارات التجارية AYN AI',
    'auth.fullName': 'الاسم الكامل',
    'auth.company': 'الشركة',
    'auth.businessEmail': 'البريد الإلكتروني للعمل',
    'auth.phoneNumber': 'رقم الهاتف',
    'auth.createPassword': 'إنشاء كلمة مرور آمنة',
    'auth.registrationSuccess': 'تم التسجيل بنجاح!',
    'auth.registrationSuccessDesc': 'يرجى التحقق من بريدك الإلكتروني للتحقق من حسابك. سيتم مراجعة وصولك من قبل فريقنا.',
    'auth.registrationError': 'خطأ في التسجيل',
    'auth.accessReviewDesc': 'سيتم مراجعة الوصول ومنحه من قبل فريق AYN خلال 24 ساعة',
    
    // Terms Modal
    'terms.welcomeToAynAI': 'مرحباً بك في AYN AI',
    'terms.businessPartner': 'شريك أعمالك الذكي',
    'terms.reviewTerms': 'مرحباً! يرجى أخذ لحظة لمراجعة شروط الخدمة وسياسة الخصوصية الخاصة بنا.',
    'terms.howAynWorks': 'كيف يعمل AYN AI',
    'terms.aynDescription': 'تم تصميم AYN AI لمساعدتك في رؤى الأعمال والتفكير الاستراتيجي. إليك ما يجب أن تعرفه:',
    'terms.aiSuggestions': 'يقدم الذكاء الاصطناعي لدينا اقتراحات وتوصيات بناءً على البيانات والأنماط المتاحة',
    'terms.supportDecisions': 'الردود مخصصة لدعم عملية اتخاذ القرار لديك، وليس لاستبدال الحكم المهني',
    'terms.verifyInfo': 'نوصي بالتحقق من المعلومات المهمة من خلال بحث إضافي',
    'terms.marketInsights': 'رؤى السوق تستند إلى البيانات التاريخية والاتجاهات، وليس ضمانات فورية',
    'terms.privacyProtection': 'الخصوصية وحماية البيانات',
    'terms.secureProcessing': 'تتم معالجة محادثاتك بأمان وتستخدم لتحسين خدمتنا',
    'terms.noSharing': 'لا نشارك معلومات أعمالك الشخصية مع أطراف ثالثة',
    'terms.encryption': 'يتم تخزين البيانات بتشفير ومقاييس أمان معيارية في الصناعة',
    'terms.dataDeletion': 'يمكنك طلب حذف البيانات بالاتصال بفريق الدعم لدينا',
    'terms.compliance': 'نحن نلتزم بلوائح حماية البيانات المعمول بها',
    'terms.bestPractices': 'أفضل الممارسات للنجاح',
    'terms.researchTool': 'استخدم AYN AI كأداة بحث وعصف ذهني قوية',
    'terms.crossReference': 'قم بالمقارنة المرجعية للاقتراحات المهمة مع خبراء الصناعة',
    'terms.oneInput': 'اعتبر توصيات الذكاء الاصطناعي كإدخال واحد في عملية اتخاذ القرار لديك',
    'terms.followUp': 'لا تتردد في طرح أسئلة متابعة لاستكشاف وجهات نظر مختلفة',
    'terms.serviceInfo': 'معلومات الخدمة',
    'terms.messageLimits': 'يتضمن حسابك حدود رسائل شهرية كما هو محدد في خطة الوصول الخاصة بك',
    'terms.serviceUpdates': 'يتم إجراء تحديثات وتحسينات الخدمة بانتظام',
    'terms.availability': 'نسعى لتوفر عالي ولكن لا يمكننا ضمان 100% من وقت التشغيل',
    'terms.support': 'الدعم متاح إذا واجهت أي مشاكل',
    'terms.importantNote': 'مهم: بينما AYN AI أداة أعمال قوية، تبقى جميع القرارات النهائية لك لاتخاذها. نوصي باستخدام رؤانا جنباً إلى جنب مع خبرتك، وعند الاقتضاء، الاستشارة المهنية للقرارات التجارية الكبرى.',
    'terms.hasRead': 'لقد قرأت وفهمت الشروط والإخلاء أعلاه',
    'terms.acceptTerms': 'أقبل هذه الشروط وأوافق على استخدام AYN AI على مسؤوليتي وتقديري الخاص',
    'terms.acceptContinue': 'قبول الشروط والمتابعة إلى AYN AI',
    
    // 404 Page
    'notFound.pageNotFound': 'الصفحة غير موجودة',
    'notFound.description': 'عذراً! يبدو أن AYN لا يمكنه العثور على الصفحة التي تبحث عنها. دعنا نعيدك إلى استكشاف رؤى الأعمال.',
    'notFound.goBack': 'العودة',
    'notFound.returnHome': 'العودة للرئيسية',
    'notFound.needHelp': 'تحتاج مساعدة؟ AYN جاهز دائماً للمساعدة في أسئلة أعمالك.',
    
    // Tutorial
    'tutorial.welcome.title': 'مرحباً بك في AYN',
    'tutorial.welcome.subtitle': 'دعني أريك المكان وأساعدك على البدء',
    'tutorial.welcome.startButton': 'ابدأ الجولة',
    'tutorial.welcome.skipButton': 'تخطي الآن',
    'tutorial.steps.eye.title': 'تعرف على AYN',
    'tutorial.steps.eye.description': 'هذا هو AYN، مساعدك الذكي. شاهد كيف تتبع العين مؤشرك وتستجيب لرسائلك.',
    'tutorial.steps.eyeEmotions.title': 'مشاعر AYN',
    'tutorial.steps.eyeEmotions.description': 'يعكس لون العين مزاج AYN:\n🟢 أخضر = سعيد\n🔵 أزرق = يفكر\n🟠 برتقالي = متحمس\n🔴 أحمر = محبط\n🟣 بنفسجي = فضولي',
    'tutorial.steps.chatInput.title': 'ابدأ المحادثة',
    'tutorial.steps.chatInput.description': 'اكتب رسالتك هنا. ستطير رسالتك إلى AYN ويتم امتصاصها!',
    'tutorial.steps.attachment.title': 'إضافة ملفات',
    'tutorial.steps.attachment.description': 'انقر على + لإرفاق ملفات أو صور أو PDF. يمكن لـ AYN تحليلها لك.',
    'tutorial.steps.suggestions.title': 'اقتراحات ذكية',
    'tutorial.steps.suggestions.description': 'بعد رد AYN، انقر على أي فقاعة اقتراح للمتابعة السريعة.',
    'tutorial.steps.sidebar.title': 'التنقل',
    'tutorial.steps.sidebar.description': 'الوصول إلى محادثاتك الأخيرة، والبحث في المحادثات، وتثبيت المفضلات.',
    'tutorial.steps.transcript.title': 'سجل المحادثة',
    'tutorial.steps.transcript.description': 'انقر هنا لرؤية سجل محادثتك الكامل.',
    'tutorial.steps.profile.title': 'ملفك الشخصي',
    'tutorial.steps.profile.description': 'الوصول إلى الإعدادات، تغيير صورتك، تبديل اللغة، أو تسجيل الخروج.',
    'tutorial.navigation.next': 'التالي',
    'tutorial.navigation.previous': 'السابق',
    'tutorial.navigation.skip': 'تخطي الجولة',
    'tutorial.navigation.finish': 'ابدأ الآن!',
    'tutorial.navigation.stepOf': 'من',
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const direction: Direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    // Load saved language from localStorage
    const savedLang = localStorage.getItem('ayn-language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'ar')) {
      setLanguageState(savedLang);
    }
  }, []);

  useEffect(() => {
    // Update document direction and language
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    
    // Add/remove RTL class for styling
    if (language === 'ar') {
      document.documentElement.classList.add('rtl');
    } else {
      document.documentElement.classList.remove('rtl');
    }
  }, [language, direction]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('ayn-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};