/**
 * DrawingSheet — wraps floor plan SVG in a standard architectural sheet
 * with border, title block, scale bar, and north arrow.
 */

import React from 'react';
import {
  LINE_WEIGHTS,
  DRAWING_COLORS,
  FONTS,
  SHEET,
  type DrawingScale,
  DEFAULT_SCALE,
} from './drawingConstants';
import { NorthArrow } from './ArchitecturalSymbols';
import { ScaleBar } from './ScaleBar';

interface DrawingSheetProps {
  children: React.ReactNode;
  projectName?: string;
  drawingTitle?: string;
  drawingNumber?: string;
  scale?: DrawingScale;
  date?: string;
  style?: string;
  width?: number;
  height?: number;
}

export const DrawingSheet: React.FC<DrawingSheetProps> = ({
  children,
  projectName = 'Untitled Project',
  drawingTitle = 'Floor Plan',
  drawingNumber = 'A-101',
  scale = DEFAULT_SCALE,
  date,
  style: buildingStyle,
  width = 800,
  height = 600,
}) => {
  const displayDate = date || new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  const borderMargin = 8;
  const tbW = 280;
  const tbH = 44;
  const tbX = width - borderMargin - tbW;
  const tbY = height - borderMargin - tbH;
  const leftColW = 180;

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      xmlns="http://www.w3.org/2000/svg"
      style={{ background: DRAWING_COLORS.WHITE, width: '100%', height: '100%' }}
    >
      {/* Sheet border */}
      <rect
        x={borderMargin} y={borderMargin}
        width={width - borderMargin * 2} height={height - borderMargin * 2}
        fill="none" stroke={DRAWING_COLORS.BLACK} strokeWidth={SHEET.BORDER_WIDTH}
      />

      {/* Inner content area */}
      <g transform={`translate(${borderMargin + 4}, ${borderMargin + 4})`}>
        {children}
      </g>

      {/* ── Title Block (bottom right) ─────────────────────── */}
      <g transform={`translate(${tbX}, ${tbY})`}>
        {/* Outer border */}
        <rect x={0} y={0} width={tbW} height={tbH}
          fill={DRAWING_COLORS.WHITE} stroke={DRAWING_COLORS.BLACK}
          strokeWidth={LINE_WEIGHTS.OUTLINE} />
        {/* Vertical divider */}
        <line x1={leftColW} y1={0} x2={leftColW} y2={tbH}
          stroke={DRAWING_COLORS.BLACK} strokeWidth={LINE_WEIGHTS.DIMENSION} />
        {/* Horizontal dividers — left column */}
        <line x1={0} y1={tbH * 0.28} x2={leftColW} y2={tbH * 0.28}
          stroke={DRAWING_COLORS.BLACK} strokeWidth={LINE_WEIGHTS.DIMENSION} />
        <line x1={0} y1={tbH * 0.56} x2={leftColW} y2={tbH * 0.56}
          stroke={DRAWING_COLORS.BLACK} strokeWidth={LINE_WEIGHTS.DIMENSION} />
        <line x1={0} y1={tbH * 0.78} x2={leftColW} y2={tbH * 0.78}
          stroke={DRAWING_COLORS.BLACK} strokeWidth={LINE_WEIGHTS.DIMENSION} />
        {/* Horizontal dividers — right column */}
        <line x1={leftColW} y1={tbH * 0.33} x2={tbW} y2={tbH * 0.33}
          stroke={DRAWING_COLORS.BLACK} strokeWidth={LINE_WEIGHTS.DIMENSION} />
        <line x1={leftColW} y1={tbH * 0.66} x2={tbW} y2={tbH * 0.66}
          stroke={DRAWING_COLORS.BLACK} strokeWidth={LINE_WEIGHTS.DIMENSION} />

        {/* Left column text */}
        <text x={5} y={tbH * 0.18}
          fontFamily={FONTS.TITLE_BLOCK.family} fontSize={7} fontWeight="700"
          fill={DRAWING_COLORS.BLACK}>
          {projectName}
        </text>
        <text x={5} y={tbH * 0.28 + tbH * 0.17}
          fontFamily={FONTS.TITLE_SUB.family} fontSize={5} fontWeight="400"
          fill={DRAWING_COLORS.BLACK}>
          {drawingTitle}
        </text>
        <text x={5} y={tbH * 0.56 + tbH * 0.14}
          fontFamily={FONTS.NOTE.family} fontSize={4}
          fill={DRAWING_COLORS.DARK_GRAY}>
          {buildingStyle ? `Style: ${buildingStyle}` : ''}
        </text>
        <text x={5} y={tbH * 0.78 + tbH * 0.14}
          fontFamily={FONTS.NOTE.family} fontSize={3.5}
          fill={DRAWING_COLORS.MEDIUM_GRAY}>
          Generated by AYN
        </text>

        {/* Right column text */}
        <text x={leftColW + 5} y={tbH * 0.22}
          fontFamily={FONTS.NOTE.family} fontSize={4}
          fill={DRAWING_COLORS.DARK_GRAY}>
          Scale: {scale}
        </text>
        <text x={leftColW + 5} y={tbH * 0.33 + tbH * 0.22}
          fontFamily={FONTS.NOTE.family} fontSize={4}
          fill={DRAWING_COLORS.DARK_GRAY}>
          Date: {displayDate}
        </text>
        <text x={leftColW + 5} y={tbH * 0.66 + tbH * 0.22}
          fontFamily={FONTS.TITLE_BLOCK.family} fontSize={6} fontWeight="700"
          fill={DRAWING_COLORS.BLACK}>
          {drawingNumber}
        </text>
      </g>

      {/* Scale Bar (above title block) */}
      <ScaleBar
        x={tbX + 10}
        y={tbY - 12}
        scale={scale}
      />

      {/* North arrow (top right) */}
      <NorthArrow x={width - borderMargin - 25} y={borderMargin + 25} />

      {/* Preliminary watermark */}
      <text
        x={width / 2} y={height / 2}
        textAnchor="middle" dominantBaseline="middle"
        fill="#E0E0E0"
        fontFamily={FONTS.TITLE_BLOCK.family}
        fontSize={20} fontWeight="700" opacity={0.06}
        transform={`rotate(-30, ${width / 2}, ${height / 2})`}
      >
        PRELIMINARY — NOT FOR CONSTRUCTION
      </text>
    </svg>
  );
};

export default DrawingSheet;
