export interface AIEmployee {
  id: string;
  name: string;
  role: string;
  emoji: string;
  triggeredBy: string; // matches ayn_activity_log.triggered_by
  gradient: string;
  reportsTo: string;
  description: string;
}

export const AI_WORKFORCE: AIEmployee[] = [
  {
    id: 'system',
    name: 'AYN',
    role: 'Co-Founder & Orchestrator',
    emoji: '🧠',
    triggeredBy: 'system',
    gradient: 'from-violet-600 to-purple-600',
    reportsTo: 'Founder',
    description: 'Central brain — orchestrates all employees, aggregates reports, handles direct commands.',
  },
  {
    id: 'chief_of_staff',
    name: 'Chief of Staff',
    role: 'Meta-Orchestrator',
    emoji: '📋',
    triggeredBy: 'chief_of_staff',
    gradient: 'from-indigo-600 to-violet-600',
    reportsTo: 'Founder',
    description: 'Coordinates employee debates, tracks objectives, detects misalignment, gates chime-ins.',
  },
  {
    id: 'advisor',
    name: 'Advisor',
    role: 'Strategic Advisor',
    emoji: '📊',
    triggeredBy: 'advisor',
    gradient: 'from-blue-600 to-cyan-600',
    reportsTo: 'Founder',
    description: 'Synthesizes employee reports into strategic recommendations. Big-picture thinker.',
  },
  {
    id: 'lawyer',
    name: 'Lawyer',
    role: 'Legal & Compliance',
    emoji: '⚖️',
    triggeredBy: 'lawyer',
    gradient: 'from-slate-600 to-gray-600',
    reportsTo: 'Founder',
    description: 'Scans content for legal risk, reviews terms compliance, and flags regulatory issues.',
  },
  {
    id: 'security_guard',
    name: 'Security Guard',
    role: 'Threat Detection',
    emoji: '🛡️',
    triggeredBy: 'security_guard',
    gradient: 'from-red-600 to-rose-600',
    reportsTo: 'AYN',
    description: 'Monitors for prompt injection, suspicious activity, and manages auto-blocking.',
  },
  {
    id: 'sales',
    name: 'Sales',
    role: 'Lead Hunter',
    emoji: '💼',
    triggeredBy: 'sales',
    gradient: 'from-emerald-600 to-green-600',
    reportsTo: 'AYN',
    description: 'Hunts for leads, qualifies prospects, prioritizes high-margin scalable services.',
  },
  {
    id: 'investigator',
    name: 'Investigator',
    role: 'Deep Research',
    emoji: '🔍',
    triggeredBy: 'investigator',
    gradient: 'from-amber-600 to-yellow-600',
    reportsTo: 'AYN',
    description: 'Performs deep company research, scores leads against service economics.',
  },
  {
    id: 'follow_up',
    name: 'Follow-Up Agent',
    role: 'Lead Persistence',
    emoji: '📬',
    triggeredBy: 'follow_up',
    gradient: 'from-orange-600 to-amber-600',
    reportsTo: 'AYN',
    description: 'Manages follow-up sequences with a strict 2-email limit per lead.',
  },
  {
    id: 'customer_success',
    name: 'Customer Success',
    role: 'Onboarding & Retention',
    emoji: '🤝',
    triggeredBy: 'customer_success',
    gradient: 'from-teal-600 to-emerald-600',
    reportsTo: 'AYN',
    description: 'Manages user onboarding, monitors churn risk, detects abandoned calculations.',
  },
  {
    id: 'qa_watchdog',
    name: 'QA Watchdog',
    role: 'System Health',
    emoji: '🐕',
    triggeredBy: 'qa_watchdog',
    gradient: 'from-pink-600 to-rose-600',
    reportsTo: 'AYN',
    description: 'Monitors edge function health, engineering calculator patterns, uptime metrics.',
  },
  {
    id: 'marketing',
    name: 'Marketing Strategist',
    role: 'Content & Social',
    emoji: '📣',
    triggeredBy: 'marketing',
    gradient: 'from-sky-600 to-blue-600',
    reportsTo: 'AYN',
    description: 'Coordinates content strategy, competitor analysis, aligns campaigns to objectives.',
  },
  {
    id: 'hr_manager',
    name: 'HR Manager',
    role: 'Culture & Performance',
    emoji: '👥',
    triggeredBy: 'hr_manager',
    gradient: 'from-fuchsia-600 to-pink-600',
    reportsTo: 'Chief of Staff',
    description: 'Tracks employee effectiveness, detects personality drift, suggests retraining.',
  },
  {
    id: 'innovation',
    name: 'Innovation Lead',
    role: 'R&D & Experiments',
    emoji: '🚀',
    triggeredBy: 'innovation',
    gradient: 'from-lime-600 to-green-600',
    reportsTo: 'Chief of Staff',
    description: 'Proposes experiments, challenges existing architecture, identifies scaling opportunities.',
  },
];
